// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHjgk8wUTEWOcXKGbnxiAt08HahXbafH8',
    appId: '1:1087379903912:web:85a0ec0e915bbd113fb99d',
    messagingSenderId: '1087379903912',
    projectId: 'myapp-5a082',
    authDomain: 'myapp-5a082.firebaseapp.com',
    storageBucket: 'myapp-5a082.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCerU7wL5BSff2RJ7w0R1RvKhPUcu96FVU',
    appId: '1:1087379903912:android:fb1ae8b30f89d4d53fb99d',
    messagingSenderId: '1087379903912',
    projectId: 'myapp-5a082',
    storageBucket: 'myapp-5a082.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFejo5IP6etJnnRq0lxUB9bRSrE2bkRq0',
    appId: '1:1087379903912:ios:34af922cd17695663fb99d',
    messagingSenderId: '1087379903912',
    projectId: 'myapp-5a082',
    storageBucket: 'myapp-5a082.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
